# SPDX-License-Identifier: BSD-2-Clause-Patent
# Generates BigFont.c for BigGraphicsConsoleDxe from a PSF2 console font
# (optionally gzipped): the glyph bitmaps plus a sorted CHAR16 -> glyph-index
# map built from the PSF unicode table. Codepoints outside the BMP are
# dropped (the console is CHAR16).
#
# Usage: gen-font.py FONT.psf[.gz] FONT_NAME OUT.c
import gzip
import struct
import sys

PSF2_MAGIC = 0x864AB572
PSF2_HAS_UNICODE_TABLE = 0x01


def load(path):
    raw = open(path, "rb").read()
    if raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)
    magic, version, headersize, flags, length, charsize, height, width = struct.unpack(
        "<8I", raw[:32]
    )
    assert magic == PSF2_MAGIC, f"{path}: not PSF2"
    assert version == 0, f"{path}: unsupported PSF2 version {version}"
    glyphs = [
        raw[headersize + i * charsize : headersize + (i + 1) * charsize]
        for i in range(length)
    ]
    assert flags & PSF2_HAS_UNICODE_TABLE, f"{path}: no unicode table"

    table = raw[headersize + length * charsize :]
    mapping = {}
    glyph = 0
    entry = bytearray()
    i = 0
    while i < len(table) and glyph < length:
        b = table[i]
        if b == 0xFF:  # end of this glyph's entry
            for ch in entry.decode("utf-8", "ignore"):
                cp = ord(ch)
                if cp <= 0xFFFF and cp not in mapping:
                    mapping[cp] = glyph
            glyph += 1
            entry = bytearray()
            i += 1
        elif b == 0xFE:  # combining sequences follow; skip to terminator
            while i < len(table) and table[i] != 0xFF:
                i += 1
        else:
            entry.append(b)
            i += 1

    return width, height, charsize, glyphs, sorted(mapping.items())


def main():
    font_path, font_name, out_path = sys.argv[1:4]
    width, height, charsize, glyphs, mapping = load(font_path)
    bpr = (width + 7) // 8
    assert charsize == bpr * height

    used = sorted({g for _, g in mapping})
    index_of = {g: i for i, g in enumerate(used)}

    with open(out_path, "w") as out:
        out.write(
            "// Generated by gen-font.py from %s (%dx%d, %d glyphs, %d mapped)\n"
            "// Font: Terminus (SIL Open Font License 1.1)\n"
            "// SPDX-License-Identifier: OFL-1.1\n\n"
            '#include "GraphicsConsole.h"\n\n' % (font_name, width, height, len(used), len(mapping))
        )
        out.write("CONST UINT32 mBigFontWidth = %d;\n" % width)
        out.write("CONST UINT32 mBigFontHeight = %d;\n" % height)
        out.write("CONST UINT32 mBigFontGlyphSize = %d;\n\n" % charsize)
        out.write("CONST UINT8 mBigFontGlyphs[] = {\n")
        for g in used:
            out.write("  %s,\n" % ", ".join("0x%02x" % b for b in glyphs[g]))
        out.write("};\n\n")
        out.write("CONST BIG_FONT_MAP_ENTRY mBigFontMap[] = {\n")
        for cp, g in mapping:
            out.write("  { 0x%04x, %d },\n" % (cp, index_of[g]))
        out.write("};\n\n")
        out.write("CONST UINTN mBigFontMapSize = %d;\n" % len(mapping))


if __name__ == "__main__":
    main()
